// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqvPCeeiIFyGHjH9R3O832__3vtKKpz5k',
    appId: '1:1027602646618:web:0770c3624ca0e299acba63',
    messagingSenderId: '1027602646618',
    projectId: 'login-demo-d3cb5',
    authDomain: 'login-demo-d3cb5.firebaseapp.com',
    storageBucket: 'login-demo-d3cb5.firebasestorage.app',
    measurementId: 'G-9ZNK9D8TRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvgI7SHnlUE2qttOdUUxICzn_Ys0Io0ow',
    appId: '1:1027602646618:android:585551da60df08e7acba63',
    messagingSenderId: '1027602646618',
    projectId: 'login-demo-d3cb5',
    storageBucket: 'login-demo-d3cb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYmD3Y1Qnmbim-AlygrKhH0hAzwshG9I',
    appId: '1:1027602646618:ios:648647f8b573ef34acba63',
    messagingSenderId: '1027602646618',
    projectId: 'login-demo-d3cb5',
    storageBucket: 'login-demo-d3cb5.firebasestorage.app',
    androidClientId: '1027602646618-snn39gch7ibv98avpn1ac7hriujp7pkq.apps.googleusercontent.com',
    iosClientId: '1027602646618-sc5u0168j3b2hm8ea94ldkqdc2bsvnff.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
